/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NQueensNative */

#ifndef _Included_NQueensNative
#define _Included_NQueensNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NQueensNative
 * Method:    inicializaPopulacao2
 * Signature: ([[III)V
 */
JNIEXPORT void JNICALL Java_NQueensNative_inicializaPopulacao2
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     NQueensNative
 * Method:    evoluiPopulacao2
 * Signature: (I[[I[[I[I[[I[[II[[I[IIIIIDID)[I
 */
JNIEXPORT jintArray JNICALL Java_NQueensNative_evoluiPopulacao2
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray, jintArray, jobjectArray, jobjectArray, jint, jobjectArray, jintArray, jint, jint, jint, jint, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
